# Generated by Django 5.2 on 2025-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_carrito_itemcarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.FileField(null=True, upload_to='imagenes'),
        ),
    ]
