# Generated by Django 5.2 on 2025-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='metodo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Crédito/Débito'), ('transferencia', 'Transferencia Bancaria'), ('contra_entrega', 'Pago Contra Entrega')], default='tarjeta', max_length=20),
        ),
    ]
