# Generated by Django 5.2 on 2025-05-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_checkout_estado_checkoutitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activo',
        ),
    ]
